### PR TITLE
CD-227790 Upgrade redis-namespace gem in order to update redis-rb gem to support tls

### PR DESCRIPTION
**Pull request by revathi-murali**
## Reviewers

- [ ] @johnny-lai 
- [x] @abdulchaudhrycoupa 

## Summary of change

 - Updated `redis-namespace` gem to `v1.6` which supports redis-rb v4.
 - Changes wrt redis-rb
     - redis.client is changed to redis._client 
     https://github.com/resque/redis-namespace/commit/1403f511f6ae1ec9a8f330298a4cacf73fb10afc 
     https://github.com/redis/redis-rb/commit/c239abb43c2dce99468bf94652a3c48b31a1041a
     
   - Redis.connect is changed to Redis.new 
   https://github.com/redis/redis-rb/commit/895cc3211e335a8fd9ba9322cd311c09eea9621f

### CODE REVIEW

**Comment by revathi-murali** [comment]
@johnny-lai Created a new branch v1.26.1 (from v1.26.0_fork) where in the changes for redis-namespace upgrade will be merged. I am not touching v1.26.0_fork which will be used in older-releases.. Let me know your opinion.

**Comment by johnny-lai** [comment]
Please update the version file (either now or later is fine)

**Comment by johnny-lai** [comment]
Just curious... should we try upgrading resque to the tip?

**Comment by johnny-lai** [comment]
> @johnny-lai Created a new branch v1.26.1 (from v1.26.0_fork) where in the changes for redis-namespace upgrade will be merged. I am not touching v1.26.0_fork which will be used in older-releases.. Let me know your opinion.

So I meant the "v1.26.0_fork" to mean that these are changes forked from the v1.26.0 main line, which technically includes these changes.

I think you want a different branch in case we need to backport fixes? Hmm... I think we should update the v1.26.0_fork to redis v6, and if there are changes needed for the old version, we can make v.126.0_fork_redisv5 later if needed. In a way "v1.26.0_fork" is equivalent to master I think.

**Comment by revathi-murali** [comment]
@johnny-lai As per the last discussion created a new branch `v1.26.0.1` where redis v6 changes will be merged.

Note: Changed the base branch of this PR to `v1.26.0.1`.

**Comment by johnny-lai** [comment]
lgtm

**Review by abdulchaudhrycoupa — APPROVED** [review]

**Comment by revathi-murali** [comment]
[lockit v4.9.3] merged via Lockit CLI on 2021-01-22 15:40:32.553413 +0530 IST m=+6.682980767

**Pull request merged**
