### PR TITLE
CD-28568 Fix issue where we are pushing job information onto "resque:…

### PR DESCRIPTION
**Pull request by johnny-lai**
…XXX:accepted" instead of just "resque:accepted"

### CODE REVIEW

**Comment by johnny-lai** [comment]
- [ ] @gnusosa please review

**Comment by stephane-pelchat** [comment]
@johnny-lai let's add unit-tests around the monkey patch, thx

**Comment by gnusosa** [comment]
@johnny-lai looks good to me :+1:

**Comment by johnny-lai** [comment]
test added

**Comment by johnny-lai** [comment]
Here is the output of the test:
johnny_lai$ bundle exec rake
/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby -I"lib:test:lib" -I"/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib" "/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/airbrake_test.rb" "test/hoptoad_test.rb" "test/job_hooks_test.rb" "test/job_plugins_test.rb" "test/plugin_test.rb" "test/resque_failure_redis_test.rb" "test/resque_test.rb" "test/worker_test.rb"
/usr/local/bin/redis-server
Starting redis for testing at localhost:9736...
Run options: --seed 61772

# Running tests:

EE..............................WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
...........WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
..WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
..........................WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.....WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
..WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
..WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
....WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.....WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
....WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
  PID STAT
24113 S+
..WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.EWARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
...WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
.....

Finished tests in 8.579268s, 14.9197 tests/s, 33.4527 assertions/s.

  1) Error:
#<Class:0x007fb63594b310>#test_should_be_notified_of_an_error:
NoMethodError: undefined method `expects' for Airbrake:Module
    /Users/johnny_lai/Coupa-Local/resque/test/airbrake_test.rb:19:in `block (2 levels) in <top (required)>'

  2) Error:
#<Class:0x007fb63596cb00>#test_should_be_notified_of_an_error:
NoMethodError: undefined method `expects' for HoptoadNotifier:Module
    /Users/johnny_lai/Coupa-Local/resque/test/hoptoad_test.rb:18:in `block (2 levels) in <top (required)>'

  3) Error:
#<Class:0x007fb6332abfe8>#test_remove_failed_queue:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/johnny_lai/Coupa-Local/resque/test/worker_test.rb:466:in `block (2 levels) in <top (required)>'

128 tests, 287 assertions, 0 failures, 3 errors, 0 skips
Killing test redis server...
rake aborted!
Command failed with status (3): [ruby -I"lib:test:lib" -I"/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib" "/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/airbrake_test.rb" "test/hoptoad_test.rb" "test/job_hooks_test.rb" "test/job_plugins_test.rb" "test/plugin_test.rb" "test/resque_failure_redis_test.rb" "test/resque_test.rb" "test/worker_test.rb" ]
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)


Note that in order to get the pre-existing tests to run at all, I had to:
* Remove test/resque-web_test.rb
* Remove the "glueoutputbuf" option from test/redis-test.conf

**Comment by tjackiw** [comment]
:+1:

**Pull request merged**
