### PR TITLE
CD-357930 When processing jobs like CoupaCron we cannot tell what script it is actually running from the process information

### PR DESCRIPTION
**Pull request by hubenias**
https://coupadev.atlassian.net/browse/CD-357930

### CODE REVIEW

**Review by johnny-lai — APPROVED** [review]
Thanks. Let's add some tests, but looks good otherwise

**Comment by hubenias** [comment]
@johnny-lai Tests were added.

**Comment by hubenias** [comment]
Cody rebuild

**Review by gena-admin — APPROVED** [review]

**Review by johnny-lai — APPROVED** [review]

**Comment by hubenias** [comment]
[lockit v5.0.2] merged via Lockit CLI on 2023-07-20 11:20:31.485936 +0300 EEST m=+7.409711013

**Pull request merged**
